/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Cyril43 (https://sketchfab.com/Cyril43)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/shoes-08158fa3333a4b288bd2746a6ba6f9e5
title: Shoes
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import {useFrame, useLoader, useThree} from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

const pi = Math.PI

export default function Model({offset}) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, 'shoes/scene.gltf')
  const {clock} = useThree()


  useFrame(() => {
      group.current.rotation.z += Math.sin(clock.getElapsedTime()+offset)/250;
      group.current.position.y += Math.sin(clock.getElapsedTime()+offset)/250
  });
  return (
    <group ref={group} dispose={null} position={[offset*1.5,1,0]} rotation={[0,pi/2,0]}>
          <mesh castShadow material={materials.Sheos} geometry={nodes.mesh_0.geometry} />
    </group>
  )
}
